# Generated by Django 2.1.7 on 2019-11-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('legenda', models.CharField(max_length=200)),
                ('numero_curtidas', models.CharField(max_length=900)),
                ('numero_comentarios', models.CharField(max_length=900)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('postagemm', models.ManyToManyField(to='post.Postagem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Postagem'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.Usuario'),
        ),
    ]
