# Generated by Django 2.1.7 on 2019-11-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomee', models.CharField(max_length=200)),
                ('sinopse', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('caracterisiticas', models.CharField(max_length=800)),
                ('animacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desenho.Animacao')),
            ],
        ),
    ]
