# Generated by Django 2.1.7 on 2019-12-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('publish_article', 'can publish Articles.')]},
        ),
    ]
